
# docker build -t airc/osx-agent:0.1 -f app/dockerfile .

# docker run --gpus '"device=0"' --rm -it -v /home/san/workspace/mmc1_pretrained_model_project/youtube_preproc_web/data:/data --name osx-agent airc/osx-agent:0.1

# docker tag airc/osx-agent:0.1 ketiair.com:10004/osx-agent:0.1
# docker push ketiair.com:10004/osx-agent:0.1
# docker -H 10.0.8.100:2375 pull ketiair.com:10004/osx-agent:0.1
# docker -H 10.0.8.100:2375 run --gpus '"device=0"' --rm -it -d -v /mnt/nfs4/youtube_downloader/data:/data -e MONGODB_URI="mongodb://root:1234@10.0.8.183:27018" --name osx-agent-0-0 ketiair.com:10004/osx-agent:0.1

# docker -H 10.0.8.100:2375 run --gpus '"device=0"' --rm -it -d -v /mnt/nfs4/youtube_downloader/data:/data -e DRAWING_RATE="0.01" -e MONGODB_URI="mongodb://root:1234@10.0.8.183:27018" --name osx-agent-0-0 ketiair.com:10004/osx-agent:0.1

FROM airc/1.13.0-cuda11.6-cudnn8-osx:cudagl
LABEL maintainer "KETI AIRC sankim <kimsan0622@keti.re.kr>"

ENV DEBIAN_FRONTEND noninteractive

ADD ./ /root/osx

WORKDIR /root/osx/app
RUN pip install -r requirements.txt

CMD python app.py
